apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.fullname }}-service"
  labels:
    app: {{ .Values.fullname }}
spec:
  type: NodePort #ClusterIP
  selector:
    app: {{ .Values.fullname }}
  ports:
    - protocol: TCP
      port: 80 # Service port
      targetPort: {{ .Values.targetPort }} # Container port